### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Kz-m** [Kz-m/protospace-34743#1]
URL:
https://protospace-34743.herokuapp.com/

どうぞよろしくお願いいたします。

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **プロトタイプ投稿ページにて、投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まるようにしましょう**
エラーページに遷移してしまいます。

- [ ] **ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから削除ボタンをクリックすると、プロトタイプを削除できるようにしましょう**
削除できずエラーページに遷移してしまいます。

- [ ] **コメントを投稿すると、投稿したコメントとその投稿者名が、対象プロトタイプの詳細ページにのみ表示されるようにしましょう**
コメント投稿者名が表示されません。

- [ ] **コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まるようにしましょう**
エラーページに遷移してしまいます。

- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるようにしましょう**
そのユーザーが投稿したプロトタイプが表示されていません。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Kz-m** [comment]
修正いたしました。どうぞよろしくお願いいたします。

https://protospace-34743.herokuapp.com/

**Comment by takumi0530** [comment]
@Kz-m さん、再度ご提出ありがとうございます‼︎
動作の確認をしたところ、改めて修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **プロトタイプ投稿ページにて、投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まるようにしましょう**
エラーページに遷移してしまいます。
<img width="590" alt="スクリーンショット 2021-08-02 17 07 34" src="https://user-images.githubusercontent.com/76197191/127826556-1e6476d3-a177-4044-b9f1-f4e446375e2c.png">

- [ ] **コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まるようにしましょう**
エラーページに遷移してしまいます。
<img width="590" alt="スクリーンショット 2021-08-02 17 07 34" src="https://user-images.githubusercontent.com/76197191/127826615-21cd04b3-492a-4e3a-8f7c-d83b49aff983.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Kz-m** [comment]
どうぞよろしくお願いいたします。

https://protospace-34743.herokuapp.com/

**Comment by takumi0530** [comment]
@Kz-m さん、再度ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
